backend:
  name: git-gateway
  branch: moar_cms_config

media_folder: static/img
public_folder: /img

collections:
  - label: "Pages"
    name: "pages"
    files:
      - label: "About Page (English)"
        name: "about"
        file: "gatsby/src/data/about/about.en.yml"
        filter: { field: "language", value: "en" }
        fields:
          - label: "Page"
            name: "page"
            widget: "select"
            options: ["about"]
          - {
              label: "Language",
              name: "language",
              widget: "select",
              options: ["en"],
            }
          - { label: Title, name: title, widget: string }
          - { label: Intro, name: intro, widget: markdown, required: false }
          - label: "Sections"
            name: sections
            widget: "list"
            fields:
              - label: Title
                name: title
                widget: string
              - label: Component
                name: component
                widget: "select"
                options:
                  [
                    "TableOfContents",
                    "Text",
                    "Timeline",
                    "NewsAndEvents",
                    "FAQ",
                  ]
              - label: Text
                name: text
                widget: markdown
                required: false
      - label: "About Page (Spanish)"
        name: "sobre"
        file: "gatsby/src/data/about/about.es.yml"
        filter: { field: "language", value: "es" }
        fields:
          - label: "Page"
            name: "page"
            widget: "select"
            options: ["sobre"]
          - {
              label: "Language",
              name: "language",
              widget: "select",
              options: ["es"],
            }
          - { label: Title, name: title, widget: string }
          - { label: Intro, name: intro, widget: markdown, required: false }
          - label: "Sections"
            name: sections
            widget: "list"
            fields:
              - label: Title
                name: title
                widget: string
              - label: Component
                name: component
                widget: "select"
                options:
                  [
                    "TableOfContents",
                    "Text",
                    "Timeline",
                    "NewsAndEvents",
                    "FAQ",
                  ]
              - label: Text
                name: text
                widget: markdown
                required: false
      - label: "Why the Census Matters (English)"
        name: "why_en"
        file: "gatsby/src/data/why/why.en.yml"
        filter: { field: "language", value: "en" }
        fields:
          - label: "Page"
            name: "page"
            widget: "select"
            options: ["why"]
          - {
              label: "Language",
              name: "language",
              widget: "select",
              options: ["en"],
            }
          - { label: Title, name: title, widget: string }
          - { label: Intro, name: intro, widget: markdown, required: false }
          - label: "Sections"
            name: sections
            widget: "list"
            fields:
              - label: Title
                name: title
                widget: string
              - label: Component
                name: component
                widget: "select"
                options:
                  [
                    "TableOfContents",
                    "Text",
                    "Timeline",
                    "NewsAndEvents",
                    "FAQ",
                  ]
              - label: Text
                name: text
                widget: markdown
                required: false
              - label: Call To Action
                name: cta
                widget: string
                required: false
      - label: "Why the Census Matters (Spanish)"
        name: "porque"
        file: "gatsby/src/data/why/why.es.yml"
        filter: { field: "language", value: "es" }
        fields:
          - label: "Page"
            name: "page"
            widget: "select"
            options: ["porque"]
          - {
              label: "Language",
              name: "language",
              widget: "select",
              options: ["es"],
            }
          - { label: Title, name: title, widget: string }
          - { label: Intro, name: intro, widget: markdown, required: false }
          - label: "Sections"
            name: sections
            widget: "list"
            fields:
              - label: Title
                name: title
                widget: string
              - label: Component
                name: component
                widget: "select"
                options:
                  [
                    "TableOfContents",
                    "Text",
                    "Timeline",
                    "NewsAndEvents",
                    "FAQ",
                  ]
              - label: Text
                name: text
                widget: markdown
                required: false
              - label: Call To Action
                name: cta
                widget: string
                required: false
      - label: "How To Complete the Census (English)"
        name: "how"
        file: "gatsby/src/data/how/how.en.yml"
        filter: { field: "language", value: "en" }
        fields:
          - label: "Page"
            name: "page"
            widget: "select"
            options: ["how"]
          - {
              label: "Language",
              name: "language",
              widget: "select",
              options: ["en"],
            }
          - { label: Title, name: title, widget: string }
          - { label: Body, name: body, widget: markdown, required: false }
          - label: Options
            name: options
            widget: "list"
            fields:
              - label: Label
                name: label
                widget: string
              - label: Icon
                name: icon
                widget: string
              - label: Text
                name: text
                widget: markdown
                required: false
      - label: "How To Complete the Census (Spanish)"
        name: "como"
        file: "gatsby/src/data/how/how.es.yml"
        filter: { field: "language", value: "es" }
        fields:
          - label: "Page"
            name: "page"
            widget: "select"
            options: ["como"]
          - {
              label: "Language",
              name: "language",
              widget: "select",
              options: ["es"],
            }
          - { label: Title, name: title, widget: string }
          - { label: Body, name: body, widget: markdown, required: false }
          - label: Options
            name: options
            widget: "list"
            fields:
              - label: Label
                name: label
                widget: string
              - label: Icon
                name: icon
                widget: string
              - label: Text
                name: text
                widget: markdown
                required: false

  - label: "Communities (English)"
    name: "communities_en"
    folder: "gatsby/content/communities/en"
    create: false
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    editor:
      preview: false
    filter: { field: "language", value: "en" }
    fields:
      - {
          label: "Language",
          name: "language",
          widget: "select",
          options: ["en", "es"],
        }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Link", name: "link", widget: "string" }
      - { label: "Img", name: "img", widget: "string" }
      - { label: "Img Alt", name: "alt", widget: "string" }
  - label: "Communities (Spanish)"
    name: "communities_es"
    folder: "gatsby/content/communities/es"
    create: false
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    editor:
      preview: false
    filter: { field: "language", value: "es" }
    fields:
      - {
          label: "Language",
          name: "language",
          widget: "select",
          options: ["es", "en"],
        }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Link", name: "link", widget: "string" }
      - { label: "Img", name: "img", widget: "string" }
      - { label: "Img Alt", name: "alt", widget: "string" }
  - label: "News (English)"
    name: "news_en"
    folder: "gatsby/content/news/en"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    editor:
      preview: false
    filter: { field: "language", value: "en" }
    fields:
      - {
          label: "Language",
          name: "language",
          widget: "select",
          options: ["en", "es"],
        }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Description", name: "description", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
  - label: "News (Español)"
    name: "news_es"
    folder: "gatsby/content/news/es"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    editor:
      preview: false
    filter: { field: "language", value: "es" }
    fields:
      - {
          label: "Lenguaje",
          name: "language",
          widget: "select",
          options: ["en", "es"],
        }
      - { label: "Titulo", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Description", name: "description", widget: "string" }
      - { label: "Contenido", name: "body", widget: "markdown" }
